# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43eded41a3d3bf5aa95d4b6224d550db063bf9a5bb47a6f6c859c03bb21b26c05991f333848b2c83741cf54898b09b64a78210b01b67c2e4237fd8a01f67519a

test:
  secret_key_base: 7f6af8aa09c0f68fe51a198d8e22b40c8d5a0d55631d067d5718784f622a35c1a1c5a0a93580633317e5d8510fd61727efc421707f4ab43e01d479914359da5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
